### ISSUE TITLE
pretrained file not found

### ISSUE THREAD

**Issue by crh19970307** [sabarim/3DC-Seg#1]
Hi, the file "saved_models/csn/irCSN_152_ft_kinetics_from_ig65m_f126851907.pth" is not provided, where can I download it? Thanks!

**Comment by sabarim** [comment]
You can download the pre-trained weights from [here](https://omnomnom.vision.rwth-aachen.de/data/3DC-Seg/models/csn.zip). Please note that these are weights converted to pytorch from the original caffe models from https://github.com/facebookresearch/VMZ.
