### ISSUE TITLE
flatten = lambda lst: [lst] if type(lst) is torch.Tensor else reduce(torch.add, [flatten(ele) for ele in lst])

### ISSUE THREAD

**Issue by TJJTJJTJJ** [sabarim/3DC-Seg#10]
How to understand your code:

```python
flatten = lambda lst: [lst] if type(lst) is torch.Tensor else reduce(torch.add, [flatten(ele) for ele in lst])

x =   [[torch.tensor([5.0]), torch.tensor([6.0])], [torch.tensor([7.0]), torch.tensor([8.0])]]
flatten(x)

TypeError                                 Traceback (most recent call last)
<ipython-input-47-2a14fe8cc003> in <module>
----> 1 flatten(x)

<ipython-input-44-7c292cd8c3bd> in <lambda>(lst)
----> 1 flatten = lambda lst: [lst] if type(lst) is torch.Tensor else reduce(torch.add, [flatten(ele) for ele in lst])

<ipython-input-44-7c292cd8c3bd> in <listcomp>(.0)
----> 1 flatten = lambda lst: [lst] if type(lst) is torch.Tensor else reduce(torch.add, [flatten(ele) for ele in lst])

<ipython-input-44-7c292cd8c3bd> in <lambda>(lst)
----> 1 flatten = lambda lst: [lst] if type(lst) is torch.Tensor else reduce(torch.add, [flatten(ele) for ele in lst])

TypeError: add(): argument 'input' (position 1) must be Tensor, not list
```

In my opion, you should want to get x =   [[torch.tensor([5.0]), torch.tensor([6.0])], [torch.tensor([7.0]), torch.tensor([8.0])]]-->[torch.tensor(12.0), torch.tensor(14.0)].

Or where am I wrong?

Thank you.

**Comment by TJJTJJTJJ** [comment]
https://github.com/sabarim/3DC-Seg/blob/c7927703aacecf8d141408f027c454c9709d4d79/network/Resnet3dAgg.py#L232

**Comment by sabarim** [comment]
Hi,

This part of the code is not being used in the latest version. However, if you would like to use the flatten function with your input, then you can fix the reduce operation in the following manner.

`flatten = lambda lst: [lst] if type(lst) is torch.Tensor else reduce(torch.add, torch.tensor([flatten(ele) for ele in lst]))`

I hope this still helps.
