### ISSUE TITLE
where can I download davis data list 

### ISSUE THREAD

**Issue by crh19970307** [sabarim/3DC-Seg#2]
I download davis 2017 dataset from the website https://davischallenge.org/davis2017/code.html , but in this code "2016/val.txt" is used. Where can I get this file? Thanks!

**Comment by sabarim** [comment]
The 2016 val.txt file is provided as part of the DAVIS 16 dataset bundle https://davischallenge.org/davis2016/code.html.

**Comment by crh19970307** [comment]
> The 2016 val.txt file is provided as part of the DAVIS 16 dataset bundle https://davischallenge.org/davis2016/code.html.

That means I only need to copy `2016/val.txt` to davis2017 folder?  @sabarim
