### ISSUE TITLE
How to do multi-classes training?

### ISSUE THREAD

**Issue by StrongerzZ** [sabarim/3DC-Seg#20]
Hello, thank you for your code.

I want to ask how to do multi category training? It seems that this part is missing from the code (dataset, train, loss, val, infer...), and only single category training can be performed. As stated in issue #17 :

Dataset parameters 'num_classes' are missing in the config file.

**Comment by sabarim** [comment]
Hello,

Yes, this is because our method focuses on foreground/background segmentation rather than instance segmentation. For more details, please read our paper (https://arxiv.org/pdf/2008.11516.pdf).

**Comment by StrongerzZ** [comment]
Oh, sorry I forgot, thank you again.
